theme: jekyll-theme-minimal
title: Joseph Maa
description: An engineer interested in making concise, accessible, and intuitive data visualizations for better reasoning about complex relationships between data.
logo: assets/favicon.png
github_username: Chaconine


markdown: kramdown